/**
 * The shape of the world, small enough to carry.
 *
 * The qibla map needs a map, and this site will not ask a tile service for
 * one: a tile is a request to somebody else's server carrying the reader's
 * address and, near enough, their position — which is exactly what this site
 * promises not to hand out, and what the content-security policy forbids. A
 * tiled map would also be blank on the static preview, which has no network
 * of its own to speak of.
 *
 * So the coastlines and the borders are here, drawn from Natural Earth's
 * public-domain 1:110m data, simplified to about a tenth of a degree — finer
 * than a globe the size of a phone can show — and written as encoded paths.
 * Each path is the Google polyline encoding of its points in hundredths of a
 * degree: zig-zagged, five bits to a printable character, deltas from the
 * point before, so the ordinary small step costs one byte. 385 paths,
 * 21 KB of them, and nothing to fetch.
 *
 * Imported only by the map, and only when the map is drawn.
 *
 * Source: Natural Earth (naturalearthdata.com), public domain — ne_110m_land
 * and ne_110m_admin_0_boundary_lines_land.
 */

export type Point = readonly [lon: number, lat: number];

/** One encoded path back to degrees. */
function decode(path: string): Point[] {
  const points: Point[] = [];
  let at = 0;
  let x = 0;
  let y = 0;

  const next = () => {
    let result = 0;
    let shift = 0;
    let byte: number;
    do {
      byte = path.charCodeAt(at++) - 63;
      result |= (byte & 0x1f) << shift;
      shift += 5;
    } while (byte >= 0x20);
    return result & 1 ? ~(result >> 1) : result >> 1;
  };

  while (at < path.length) {
    x += next();
    y += next();
    points.push([x / 100, y / 100]);
  }
  return points;
}

/** Coastlines and island outlines, as closed rings. */
const LAND_PATHS: readonly string[] = [
  'hsJfsNtB~D`ZOxFaAlBaAqZX}FwCoEpA',
  '`b^zoN~JXdGeA|FgCwBkAsJ^aJdCu@xA',
  'dyGxfNuFtAuAxB_@zDzRnBxWvAxMKdGcAa@qAkLu@kDcAqMwHoKk@mHj@',
  'ptVjjMaG^oFc@pBdAzDr@tGOfEeAi@cAoFb@',
  'voWfjMqHlAhSqAoCi@gEl@',
  'riRp`M{EZyEWuBpBr[CjEe@hBsA}Ba@_Ph@',
  'xjLnzLWxAxAvCjM`AdGCaBmAhMv@vC{@JqAcJeBgFFy@eBGiFqB}AwD_@iBhA}FtI',
  'hmJ|oKvAj@rC_@bDRxG`B`Bx@ZlAKjA}A`AdI|@~IvE^hAqDpC{HlBwDdF}AbA{@hAYvDiCfFZhB`FrCjGZpEfC`a@~D~CpAnh@N}@lAqHb@_Fv@{BdA|E|@xIS|Gr@P~CiF`Ak@jA}FhAgL^q^rDy]tAiU|BeHfDw[_EcWiBqNC{ZhAaCuAuGy@yNCq{@gEbFmC?iAdd@f@t@kAYsCyAk@oR}AeNsBsDoAcg@oB{]cEkJ}By@mArEo@gAqAcC}@wRuC{CmAaB}AoCu@oFHaBbAmFFGkAeBmAwERq@hAoFJ{Ny@cFJuApA{EcAw`@gDeHqBuCr@oE[aGbDaFe@yAmAkEw@eGJoAhAcDiAuS[uLb@_F|B{Ec@kTKs]_DwCw@_FoDoE^mAdAkDn@oEOaHxBkEo@eAuAcKeBmLaA}MeC{DVuH}B{DBcDm@g@gAgDu@cPuAmJ\\_Dv@StAgHxBoFViHjB_EJkIwB{PxAkKLcDnEFr@TxA|I|B[lA_FCZlAbEzCwC~@gFPeFa@qDyCiFwB{CiDsVqA}CwCgCiA}U_FgERwJk@yEJqCu@eBeCgDrCgDf@e[G_Iv@cQw@oEZmRqIyGpAcK~D{JBoLq@kHqB_FGsCi@}Cd@qF|B{EGwJdByFRoEOaH}BsDOcKn@oJ_@gJf@kKaA{Wk@}@sD}Bt@a@xAuCtCgD`@_b@]eNVmC|@f@hAaCz@uL`B{U~AcFB_CaAyNbDyMj@aBlAcFn@wCdA{b@p@}RpBmCz@VlAfJxHdG\\tBfAbGh@xAlAxGhCbCzCNdDyF|EsJZoAtAt_@pAhDpB`@|A~DtCiG`AeBpA_LlCm_@zDcB`B_Qh@{DhAiPq@aXlB?``@~heA??a`@{DqBgJ|@iGeAuHtAiH}AkQc@iQhCy^pBcWl@_Qu@qYf@aN|@{`@qBk@}ArWGdSm@fDoAxOi@c@yAsC}Cd@qAlIu@vCeAtH_As\\SaHbAmTeC_DaAdAqAfPqBfc@{@`CiA|KcC~@cFwGpAeSm@cDtA}HSgVcDmHSFiAfAkA{@eAaGc@uBbAwOyAkPWyUeCcHZma@WwPf@aZ?qGG}LyAyFh@gMiBgIfEoEy@mFhAuNlAwOm@mYdAiBuA`FgCbGOnBkApB}Ek[x@kEz@uAdAmGJkWyAkEl@iGOkDwCaDxAeFb@{FScDlAgVhAiFoCgElAqGSuIlBiGS{K}AiWmAyHiBo@uAVqAvFqHHmAQmAmD}C]mA|@cDaByAwO_GmAuAkFiB_EK}B}@oH}@cGqB{CWuBr@jA`AhEx@',
  'lfLpoIcGvBwGp@xAbB|DHdBeA`AnAjD|@vEUpC{@pE]xFmBlEkBpG_FeUtFgByA_AiCwDqAoCVoDpF',
  '|lJj~H_DxAz@dAlGz@xAeAhDxAbByAoFwBiDp@wBoA',
  'gvLtuHpHJDiBk@{B_C~@}DVp@`C',
  'wk[|}F_EdAiGaAwBLMjFbAdAT~CdAu@hChCbDOzBkDXcCrBmDC{AcCP',
  'kx`@v~Fm@pAmCoAy@rA?rArH~HiA~AxCBjDhAdDlI`GpCvDC`CaAvEM`@iAkBsCyFeEaCc@yHuD}GoH]mBkC}Ak@tA',
  'iba@~`FqCpECgCyAt@]vC_D~@gCNqBkAeBVlBdHvCCt@z@QtAjExGxCnA`@s@rA]sBcD`AmBvEoAEgAoCeAY{GjAiD|FaGpAmCiAOkBnB{Cr@w@pD',
  'os_@niCjAn@|FoCbGwFZaAuA@oBbAcLrI',
  '{wHvsA_@nFs@|AR~Ab@x@bAuBd@z@e@rCPtAt@l@JfDrMtj@pIbCpGyBv@iBJqDdA}CRoCc@oC{Ac@AaA}AwCQ}BrA}ENwDeAoB[}BsJwAwGmF{@cBZuAsAVoBiCAwBaAyA{BjDq@bC',
  'g`[~tAgA|C_CkAaD`DRxAk@jD]`Bq@Xu@hDRfBaAfCkN|GXn@qB|BmAvEoAk@oAvAq@_@a@rEgKhJw@~CHlF_BhDJpDvAlGb@`GvAtDrC`BfEhLjAbB`A~IrBbA~EFvDpArEbD~G{B]gBjBd@nDnCpQ}C`C{BrA{F`BqA~DWaA_Bn@uC`BjCpDb@gBmB]sBmAaBNsC`DhD|BbAjA~CzCqAEiBdF{Ec@m@~FyBjCE~D_BdJPfNhC|DK`KrCnBxDfHTnDc@xG^tBhBx@IdEvBtGE~HeDCsBcBY_@m@BiIhBiEVcFrA{DxAoAV}ClCqFwAtAbAyD}CfC@eBdDyGyAgGRsBqAoCOvCsAiC{KaFqCHwGaBqA}@oBDqE{@sGgHM}DkCgDsAjDuAg@fA}A_AaBwAj@WwC}CqDcBa@Cw@wAVAq@yDw@aGpE{FRh@mB_B_DyAs@^q@wAqBwBgAgBVgDe@BeBrCaAkB[mFbCgDp@y@S{B|@mFmA{A`B~BzDdADWnA`CfEMv@yHlDuFzDaDp@]|@_EbAcCcAmAcEuAmGb@kGYwCe@g@\\aAyAqGkAiAw@`BMzBq@XGrAgAbBGxD',
  'oqV~~@rABhGkCyDg@oDxBJt@',
  'whWj~@jDj@VWgB}DeEoAWm@uJmAkAX`MdE`CtC',
  '{_Vrq@gAr@{BOq@tA|M~@cAqBmBAu@eA',
  'c_Wpq@ZnBlHv@hGW?iA_Dg@{Bz@wHyA',
  'gf^bs@Gf@tI_F]S{An@cDzAo@~@',
  '{eTji@_KRk@qAqJ~AiA~BkHd@uFtBdFjAzEoAbKItPcCpAXlJsA`@uAtDMgC}DsFHsF|AYfA',
  'gm]ri@v@RtAkAvA_Cj@wC[SUz@{FnFZv@',
  '{t\\fa@fBN^v@rE~AhB?tGqBO}@aHL]_B[EShBqBMgDkCTuBwBCg@^BnBbAxB',
  'mnXhRgAxCfDqA`LKo@mBuFG{Ex@',
  'c|\\b[|@t@rAcElEuCnC{@w@o@cGrC{CrCWfB',
  'keYdFw@bIoEvBeDsEeFyBqD?_IlCuEd@kUzFyFjE]tBmIxBo@hBvDTk@dCqD`CaCrEsBEFvAyC`@z@d@sErATx@bCLp@s@tJs@jGmFfBmDdGwA`HzBWpCzCdA~Hi@pDcDhEg@p@v@|FDuAaD}Bw@r@yE~AgDbKgDdDQjHwDx@~AlAPj@gA@wAvCaBwEgAmCBNu@dH?lAuBrDe@rAaBmGo@eBaAaIpA]hA',
  'wmW{G~CdEtCd@`Ee@zNd@ZvCsDpDkByAsJcANzAvA]tAtBnDjA{D`Gb@bAsDdF@bChBx@lAeA_BcDbElAp@w@YkAnCuBMaEbCz@WfO|BZtAy@w@wD\\aErA?|@iCqAaCkD_PiDsC{Cz@{FXeFGeEoCa@j@',
  'icXaFHlDfBS\\xBqAhBv@VnA}Bz@_Gg@_DaAgAMjBuBPSpA',
  'ktSpc@|EBfDeD`GcDjF{GzFmLnDeDbCgIrD}BfBkDfJkIPeBuLl@wRtRkEBgDfCsBfDwCzAnA`DyDhAgBzFqCPaB|Bp@xFFrH',
  'w_VmJ_FxDlFV`AfCGrD~DhCDdEjApH\\eAbFxAlAyBlCKbB_AlFfAhAaBfHK\\kGbBw@~AiDZoDWwDuBeCsCdAyCe@g@iDeIoA_IgJcIwFeB{CoAAeBdBItAiHrBLlAdCHc@`BrCbApBtDsCzD`@zA',
  '{tWqs@_@rFbAvDhAkE|AbB_ArCv@|AjFsBv@qC{@}A|B}A|@pA|AGrCnB`@y@mAgDkFcCeAxAwCu@_@yAmCEJyCaD|A_@nD',
  'szNwe@lDl@~A}C`@_HyAcIiClB}D|I\\nErAv@',
  '{eWg_AbEzFzBiC{AmBU{BmBK^dCsC_ER|D',
  'scVgy@hG|DkJqKgBeEc@bDlFtF',
  'koW_kAw@|ExCs@u@|D~Al@FmCz@I^yBuBN@iAxByC_EBu@jA',
  'guVsrB{Bv@}@s@Qr@`@pAeAnCt@dDtB`A\\`Dk@|CiBTwAWyFnBPjB_An@RzAzCaBhAgBr@fA~BuBrDZbBk@IqA}@s@z@m@XfA`BqBd@uGqA`ASyHaAuDwB@',
  '|xK}pBr@p@hGDJsA[]cD@eBNc@f@',
  'r_NunB|@`@`FiBWk@sAMsDViBn@a@t@jCB',
  'rdMe{BmD^Wa@{C?kDl@c@fAmBCDx@wAFaBhAhAnA|Ai@|CApBp@\\q@`A\\nAfCr@_@Hw@bCa@vEA|Ad@jB}@Q_AoIh@gAk@zAuAAkA~B_@m@w@yBH',
  'spTwsBjD~AbD}@DkDaByAyEw@sBBk@jAvAvAl@rB',
  '~pNimCoAhAyDUmJbGwDd@Lv@sCHuCpAVl@bCXnPJeCmBnAs@`CMbAy@n@qBnBFvF_BbG]dAg@iAq@bEIlCfBrABZn@vD@mFqDmHoAiIN{DbA',
  'pcNosCp@Hp@sBjAy@k@}B{@FeAdDArB',
  'ktVmmCtAbDhBgDTuCsBcEaDwCyAz@xCxL',
  'ohYmtEYbApBxBpA_AdBl@t@tB`Cy@A}AmBwBqBVqAsAsCh@',
  'cwE}}EfCrASt@jEpA`BYl@oAkBI]o@oCBuD{@',
  'csCe~EmBbAoHBB`@kBWXz@~GNC_@tFg@e@uA',
  '_`B}mFfA|C]|@h@dBtOeE[gBiFRcJg@',
  'qx@q`GwBlCZfGzAKnA`AjAs@FqFl@qBmBHcB}@',
  'cpZcgFjA~Ca@bBfBjC|F|A~IJ|GdFdCmAFuCzIj@jF~AhF@iErCdCrI~BrA`BmAq@sD~By@nAiC{D{@iB}BgEgBsCgCmK{@uEf@oEaJeC|AwKuG{BsF`@_FuA_CsEc@kBtGD`DvDhEClE',
  'wz@mfG`AxCxAg@n@gCi@iA_CkAa@jD',
  'mb[asGkCh@mCsAk@~EfHt@nDdExHgCjBzE|E@ZeEaByCuEKuBoLiFnEyCbA',
  'zlK}aHiIT`BpAhAJ|FsAp@cAkA}@eA`B',
  'haK}qHbJy@xD}AeAQeGp@kErAEb@',
  '|bWenHbBZhI{Ax@eArDeAb@w@lEc@jAmBOm@gO|AgDbDgErAqAlB',
  'x}Iy{HdCnDcCcAeCh@dAdAoDv@}Aq@eE|@|@pCkCa@wAdFrAnD|E]k@cDv@WfFlDvBGmC}A~Do@zQD\\{@{BeAtAu@gDyBmE}H{BqBmDcA{AFnCrD',
  'l|XwpI_EOz@bFmD~CnA?dHuFd@wAK_A}AX',
  'y`[e|HgE`JfHaAxB`HaEjEBjCvCwBbCxCb@gDUaEVwEo@wCGiGtBeEQoGyD{AnA}AwA[yBdIBbEqAhE',
  'li@seI`JtBzG]aDoEfBkEgLyFgDGuEzBjBfCa@nCvCpD',
  'inAqzIvB`DpEoBZsAeHaA_AbB',
  'h{\\_dJfElAdBs@\\}A_HeBeCLsA|@lD|A',
  'xQomJrExEeLYr@`DrDrDmEJcE`GgC^sDpHqFd@V~BdBx@oAfBrDfBjG?rIt@|Ag@bC|AvDUlCjAhBg@eHqEsDk@xH_@x@oAqE}@lBkBe@cCiHR[uBfC}BpFa@n@u@gAyA`Au@jB|AHaEdBeBgAmE{CaDoKA',
  'zi_@muJxB^|F{AeEa@_DPQjA',
  'z~N}fKhFlBjCCj@u@sC{AqG@Bd@',
  'hp`@smK_R~AfD~@bFoAnDJn@QKiA',
  'fsOkyKc@vAgB]sPtDQ~AqCOoC`ApD~@vHo@nByA`NpEdAuBlGRmDcB}AsIoCN',
  'tyAk~Kl@`CaFfCbGxClVjDrX{AcEwArLaBcJe@H{@bLm@gCaCoH]uHfCoHmB{Fx@eIkBkIL',
  'dyMubL~EHp@aBuAoBuD[}Cv@TpB`Cx@',
  'xda@c_LeCn@l@oC}O\\gKxDdEvAfIRBbEpAh@xDEvCeAhGy@l@wAhE_@bFXjBeAi@iAlFn@yA|ApBrA?{Wu^|IN|B',
  'xtQ}nLzBdAlG{@`DTpGyA{HsCkIzAuDpB',
  'x{a@azLdGJ?iCcEG_Hx@|EjA',
  '|tPkqL?jEiG{CoF~Bz@tCaEdCoEoCqCkDK{EcQj@kGbBK`BrCjBkChBX`BdKjCvG\\lE{@tHbJfFfC|GL|CrAL`CfFVtFbDvE~ElA|CHfFcH`@wDpIwGe@sJtAwIhDmMjCcP\\`@lD_AfEoC~EiH|DyC_AkBmEfB{HlCiB_I}AaFkCoBiCNeCfCiDrFuCkFqEtAuDbAwHkCm@cPhAeDs@oLtD}@lAcJNDfDaAzFwD^oCtBaHoB}D{EeC}A{R`TnA|B}LbF}Hp@aC~@mAhD{CXoAjAO~E`HpCfIfAzFbDpI^jLi@zNJfDnC|FvAdO`MgDa@aIeGcLeDiHSqD`B|DdCaClJcGbBiI[gEaFMpCaCfAvF`C`SfE|EnCvCMFiDyIcD|O\\c@`AvR`FpB`CZhCcAhBqADRiA{@l@Pv@dQrAdDx@eHe@y@d@tGz@~B?EW|@v@{@Fj@nCpCxCLs@lB{@yAnCCjAnDjFk@oCdBkAVeDd@tAi@~B|B]cC|@G|Dy@Lo@lG|BrCnEz@`CrBbBLdBhAZ`AzE`CnEtE\\lCc@hCyCxHAtA}AfFLrEp@xBz@X`BW^wAjAm@dFsKi@cCv@mBzCgDlA]hExA`GwCjPNrAZe@x@BnAi@f@d@XhA]hAd@pCEtCiBlDXpCm@zBLfDl@tDrCdEtAlB~Al@xAGhFe@bAnB~H`@lJgCfJcCtCo@pBmA`BsEt@qArA}MoB}FsBaBwI{IaBiHIo@h@F~AhBtBn@xBc@b@nApFp@s@h@B?\\e@?p@jJpB~BaDf@k@a@gERsDq@oBV{AUyB^_EpBs@t@X~@ShAbArCIdF^Rb@rFqAjCqFlFBh@cBEu@n@qHgBcA{@uEd@eFtCeBDuCkCsASe@kFqB{A}BCOi@}CNkIqFeAJs@t@j@pBtBVaAxA@fBvArBiA~CwAMk@oC|@eAHwCwFqAX}AeA}@gAjCkCBaClBGbAgKSqBxAyCVoB}@Aq@gNOhDz@cA|A_DNwC`B_@~CgBCqEvB{B`CEfBiAByDfDoFf@Uc@aDOuEt@wEdAsEfD_@pAcAGaDjMkB^ChCtCdD}@z@aJ^GfEwCcCeQ`EaBtB^lBgF}@eKhBiHGgHdD_G~EyCx@iDFgA|@eBvJnAjI~JvK|B`FrClDp@Bv@pCMvJlAvL|@lAb@jGhEbG`@nE`DtAn@vBvE?zHjAjCxA~Ex@jF~ChDdEZrCa@nBrAhHjClB|E~IvH|FxA|DzEnF`FlBpCg@lBTvDuAfCDxBmBLfB}FjDXhC{BtAH`B~D~FfHjBpKh@zESi@tBf@tCc@dBvBdAjEZ~DiAlAr@[fEgCz@kB_A{@fBvD|@~C|BlArHzD?zCdBx@tCcEpC_Eh@dApDjFpB`ChFtDlApA|A_AnEeCrBdGKtGxB^xDtH{@|M}F|@}Bw@uBbBcCXuIuA_EqEyClHy@}DqDcAkI}EdAgB}KdCs@|@xF|B]aCoS{AgCx@cEN_FsAGeGaSsAiHl@kH{@cDVwFsBsFcDaf@LeIh@yGhEsBNqAjKgE`OuIpAeD_@y@zTsf@hHqE_AyA~A}D}@kC_D_CiBsCj@wAjA|AvBwAi@w@`@uDeA]oB}FLqAuFyBX}@iAOFcBm@gAcBM_DeFhAo@e@sBj@uDi@u@^gDpCcDj@kBq@u@zDgCvALf@dAzBv@Rh@_BjBrAv@|AH`@wBX`@`AKf@oAzEc@Dj@bCkAf@i@OmAjEqBJy@t@c@Mx@f@n@lBiAZg@[{Bv@]m@e@fKkJU]o@N`@_Az@OTl@rBAhLuCzBCfEyB`FwEhGsBtJlBtYoHxEuCzHiArA{AtEqBbB}Bn@_BaASRy@m@s@?cAvCmGxM_NjDqAb@o@]{BzEoCp@kCjBOpEiExDoJAkAdI}B^pAu@tFwGxGYbAc@Cg@`CcF~EcAxDqBrDIhBaBDwCtDB`@vBhAr@yBxJeGV}FfFwCZXlDcBtBsBaBCiAkAGyAxCmCtBw@nF_LrByG~BqB|AWTy@bLsBVmB`EgEfDuGGm@rFiFZcDhBkBk@eDDkD~@yCmA{Do@iJb@kGxBgGWg@aHbAiBzDq@s@bBgIjP{GjJqAlBqD[yB~FuAb@_DnFqCDeB|GkCv@mD`GaDjB{D|NQhFy@|KoEzOkBtGNtRoD|Eh@g@hCbVbDZuByAcEsE{@t@q@~FlBfCdC~GlCqC`BzDlC~KpCp@vAvHfB|@|AhFrAhCMjP|DvIx@\\a@sRiGwFUaBqAuMeFa@wCeBuBdFz@`Aa@jBhA`CeBt@fAjAcBdEnAzB?NwBc@gA`CgAbGd@pHmC?oBxCuAmAsBaDmBgAgBaDMgC^aD_BqCNwC}@d@yAnBc@sCmAlIl@|@j@|Ck@xGTdHo@pAoA|FsBwUuDcD?ZbBeLG`D{BtFkAlIwDpG_AoBgBaJG{FyAo@aBkE}A}PoBwDLsHkBmHh@qCxAwAe@qIJJl@qH`@kES_]jBiG_@ik@xFaLqCgHVsRgCgCpAuCm@k@}AiCRqIrDkGgCYvCuF_@kA{@qFJeW|CuMRmGdBvGbBgJh@eUy@uEvByEeBjEsA_CcAsK]iJzC_FOaJxAyQYV{BqDc@uHbA@|D_C_DaDDyAiEtE{BhFoAO{EkFqCgG^iEvAoG`FpD`BsJf@',
  'phU_hMbB|A}L}@uGdBaFeBuD`AcDbEcBsAlCkEoD]gE^_FpA{DnIwT`ETvAfIN_CjAbAhA`UuA~QnA|Yn@jB}ApGu@pDTtF}Cw]qA`Km@dUJhBiAoMoAtH@zIs@qHeFwOwBkEd@',
  'blS{iMnDbCvHkCoIc@wCj@',
  'b|M{gMQt@fSPtGuBIgA_BMiMTwIlB',
  '~{OghM}C|BwDaDyNqAwIlE\\bCkKy@}DoAmUbEYvAsJm@oE~BaNlAoDpA{DxDnJ|AwM`C}Hj@_HvDyHL|@jC~IfFtFuAxH_EbGXVpBsPdGaCdEbAnCpVwEiNdH_@dA|OoAjLsBrFaBeAw@jQgEAx@`Q^hDcAcCsCsW[`AgAeAcBaGaEv@yAjAcApH_BtKcA_Cs@rE{BnDK|CcAhBz@jJXtUm@jVwAdDeAoE{AzG?~@kEyCqDmEqAcOs@pC~B',
  'frRolMoFh@cJYs@x@xD~AmHtAb@rDfIlA~DQhCkApNyCC_AwKVzEaCkF_B',
  'o`[qhMjV_@}DoAyFQ{GjAWt@',
  'neQyeMtEtCbFGzBoDAcBgBsAgEu@}Wt@hHpDnFf@',
  'zoVg}LlObBhBwAlMiBmKiJbEyBcT_@}Gh@}NHyKlCdV~DvFjC?rA',
  'am\\gtMdFlA~HQrJmAo@aAiZrA',
  '`hQssMlBlArOcAiByA_Hu@wFdC',
  'yi[gwM|CrC`VEhIn@lKaCkBiCgGe@oOHsUhB',
  'rfRo~MwCzAGfBzArChIRtE_@CsBfINL{CwEDmHcAwGJOY',
  'hcTg{MmAdAqD_@qEFc@`BxB|AdT^vNtAnHDXaA_LwAf[VvGc@oGcE}Dw@qPbAcJtB{IN|G_EwDgAmETcA~A',
  'sfJ_yLbWGt@yAhJs@ZkBkEk@FkBmKkDvDW}MoDt@yAsa@iFySe@uIiAeKYiCnAdC|@fh@`EjR|DbRbKg@dD_KbD',
  'vnQ{`N}E~@gK?mD`Al@jAcJzAqPX}Hk@{UAuEhAm@rA|Br@hHj@xo@OrO_A|AoEfEwA|KWfF}@iAqA}KJ',
  'fuUidNZxCxCdAlZ|BlGk@mVuGcQ[',
  'q{Sa`Nu@`BuDo@iQ@aM`B_DhAn@fB`[dF_PlAsDe@eB~BwAq@_I_@aS^o@|AcY\\KyCgV`@aIhB{A~BtBrA{F|CyHnA_EqEaIxAsIu@cK|@qCw@gIZnCyDgGuAmw@`CiDtBkOxCgXe@mK^eDrAVpCuFv@kGg@{U`@{JU{IpDwF_A`D_CwAyA}Rv@_LK_Q~AwGvA?zW`GxAbGOsDhBwBdD{At@WpAr@t@tJk@~UlDrQdGhAzA|GiCfOzCzAiA~DtAjG[~@bCnF`EEnAcFj@XbHxDFtAdDsAtA|IfBdAbFhHn@z@jE~GxDhAiCdE_V_BuGiDuBI}AuHm@}TgMgJ_D_DyGpFNvBdDzNzEbDuFbObArNlIcDxBpVhAMoCvH_@vFbB`Rc@pSz@dk@|YyHXaBzBaEj@_CaB{EJaHzEEhDzCfEPlFxA~HlH`H`AhC|SdQhGtB|B@|B_BjGpC^`AjAKtAbAz@bAGnCvEhCzEtAZlB_EvBkDjFq@`CAdFjAlBrDd@~CpArDPVkBe@uCvAqEsC_@hCkD~Ae@pAt@Fe@hBq@eBoBSoDpEkAvGx@rC|AvEt@kB{Ah@mA}CeChBiBnKpEzB`CbEHdBzAiBfCcD^ExA}Cx@_FmCqDlAaCD_@fBzGv@zAjBbEbBdBjCwElBmAbEaGpIBrC|Bt@o@jBuB|@pA~HlBPlNlUhP`J`FTxBxAbAaApBbBvGbBpE\\dArElBJr@qCm@mAjG_AfJjEfD|Dj@hCsIvMuDzByB~C{ApJZ~IjKdGzK~IfA_Cw@gCtCqBdD[tDwHrD{AjDB]{CnD?NzElDtMMnCaCDuBbJoBpBwBVkGrFsAbCH`Fa@zDeAt@oApDBbAlCJhLqHVeBpBeCZeDfAkBUqCj@sAnAmA`@aBjEoE^tBd@oBoA{HPuC{@wC`AuBOyEpAgBbBkNvAeDdJrFjFaAcAwFh@yDzCgFWgArBYlCaDjBmHpAuBvDGQrA~@lBrAg@\\b@dCg@ZhA|Jd@IvChBtB~GdC~EjF|I~F?zAtJbCx@vCs@hLtA|D?rIfBHxAvC{@`AtDx@bAfCnAv@|DyDfDaNpD}GrAwJtDqGlCcS?qFd@{D`HvBlCWdGqF_BgAx@mAhFiDrCq@x@oCzCyCl]dArXcCtAuF~Aa@`JbCtFaAhEyC~Dy@vGgMjB^~BaAhAlAvBIi@xAPj@oCbIaBl@a@dAgCrAFtCkClFLqCu@iBw@S{@|@CrBj@tBe@jAc@GEt@}C_@}GJuMgMYPl@vB[|CyAfCmBfAiG|@oCtDgAX?j@fGvJzAIf@n@ZbGzAAzBjAR~Al@h@zB?lAp@?nA~Av@lBSpJdCj@zCfOpDpDlCrCAtBrAvIz@~BtBlHJr@sBEmB`C_Hi@I^mHz@}@NmAfBgAhBgDv@cDhCgCxAa@bC}DLaGrB}EhEwBlBeGfJkNbB?y@_HxCnIl@`@zCyCnC}GRPqApEqG`O}HxLf@b@G`CkGzE_AbEj@b@[lEiAnFyDxBkD~K}J|GkLbLDrApBl@uCzAaCdDaB@wKkAyIoBqDIeEq@}AcAkA?JrG~H~VtIbOjFnGjT`OzEpFxAvClCnAn@rAjALZlC~@nAf@dCnA`AzAtFKpB_CfAp@jD?|CwC`IiAj@_@xAWlTc@`BhCxG~BzBvKlDjOtLPnC_BtCi@pDa@Id@`Ho@`@\\pArAfAtKnDvAhAQrAs@LzA~Kr@xAlD`C|FzInJdIvCzAtHvAXt@xB[`Bd@xEg@jELvJnBzBjAxABtAgA`ACvAwAFZXkD~@eC_Ac@DyCtJgRtCwClAqC~CgS\\{ItDwFrCkJbDcE\\wG[oDoC_MaFmHKeG`DwHgAyBdBeIbB_CQe@nAsEtNcQxBmEiCgLb@]aB}JnAcCxAa@h@yAp@]Au@fJhB~CCjB}B`AoCjCcCjNX|V|GrDw@dJc@jFb@pI`CxAClE}AfNgKdE}AfBkBz@{EbDeEdB_Ar@eCbDsBtAKfBaCl@cEYyArAyC`BgAuAe@qCsFPiBw@cBW{Dl@gHScBr@_BfBuAQqDmC}CLcAeAkCqD_Du@sBCkBgAyBeCiA}BkEgBoAyDUiLcJp@yFeBsG_CgC}ImDcEiIsC?wBtA}DMeHl@_EkBwEc@}BqAaE}@}Ss@cB\\{DmAuEAqAl@gCKyEoAkCVDdBiDiAMd@bB`B@zAeAp@XlDbCbBe@jBgBBq@~AkA\\iFdAsAQgD`@iGvA{ApDmMzBuE`B_EoCl@wC}@aBoC}AiCYoGf@cAxAoIx@o@`AkGCaNnCmFwBoDQmCXu@bBm@aA{Hx@}CsBoA_GoEiJPyCo@qAhA{AkAiAxBNfDm@fCrBnHT`DiBvEGl@rAhCV`EkBxEBtBeEpCoB_B{C|B}A}E_EsHGsAwC}JXoFaCgFw@kIC{RxEgF]kDPkFiB]sAp@iCpBgAnBWfIeFbFkAjDsBoC_@eDgDnBoAgHoADk@pIn@dC~@zDHjDjAKzBaBn@kEKf@fAxE`@nGrBlBg@k@}AzE{@cFgBx@m@vHq@JkAxDXdF`GEp@`Bj@z@Qv@nFfBrAhAlCyA~DmD~@b@p@lFHzFhDz@eC`FYrFr@kCnBdB`@nB?hBgBb@j@k@vBcB|AjAj@sEtCAnBvDs@y@dB|BRiApDbC@bDwAlBcHrDmEr@sBlBaAP_Bk@eEbCoBzPuFhDqCi@OzAsABcA~B]|@tAx@cACcAs@U~C]`DfALzCaAdB{DbBcBdD}E~C}C?o@j@v@f@eIbC_ElCd@fAlB}AlD_@rA~BoCjAVfBpAJjBhDrANi@gDk@i@jCyEpAWz@uA~Be@tAoArCKzCyA~HuF|@eEdGyAvMvFhKu@bH~@JlF|DbC~Fj@P`AxBnBlA`DmApBrBxAh@`CvCf@lCxCzLAhEpC`BO`CuDxD_@pAr@fB[fBT]{CP{BxAQn@kAOaCoAiAw@gEr@_FImCpAwAyGoCuUdAiNCgBwBe@mK`JwHpHmARoCaGk@oIr@|@cF{DtAqM{C{@cDoIoAeBu@oDeHoGsAgDDe@i@gDKc@j@gCaBl@kAFoBpAoBDkEyAqBoDKgFoBDdBz@`AWv@kB\\n@jAz@UnCnCy@lDiEn@@dA{H{A_IlC{TyEgE`@On@_E@m@wAsG_Ah@gDEuCaB}B{DcA_DrC_DC}@mGhAV|BeAPsBwNsAgLXcFmBpE}AhJNdTpBrBkB`EaAk@eE~AsD_BsBsD}BoQaGTsAtG_BvIx@`EhC_@zB~TjIpCxGmCjC_EnBvD`FnEl@jAnIpBzDpFSpB|CfFH|@}D~H}NdCyBjKfFhGl@rGeBfAuE~@mMwD_CoOgDkKoEmYwSsZqKwLwAgIJqHeDkJFgJg@oRrC~Fr@yE|BmEeAiIxBaPn@sV`FyC|AMdC|EfBfIt@zZwCrCXeIpCYhH}KnBY_BzByAcCgAaNzBiDo@fCsCqMcEyDJyDdAsBiCdDuBaBwBrC{BoP~@qBnBzFV?nB}CbAsHi@q@_C{a@kGuCHbExBwFRmCcAwJEgHqAcFvBcFcCpEsBgBaAmQz@i^bHeCiBjEgBBk@pFQaA_BjB{CD_AqJsDcCuDsCg@qOr@i@nB|D`D{B~@_AjCl@pG}ExBtAdCfKzGcF\\oAgA{Es@u@aBkD_BrBqB}AcCzEOn@oB_DgEbGcDeJeCl@mCcBEgBnBlA~DuEd@zAoCoIoA}KIqJpBpDeDRuE{Ig@q[Q`DgBgFcCeFCcKcBoOYaAw@mOQcDj@_MiBoJBw@uA}DuAwMqAwI`AnGn@cM^',
  'niQocNpMGt@u@sK@kCd@VT',
  'toTsdNrJx@fH_AaD_AcHSyG\\bAz@',
  'oyCqeN|LpA~Io@iCs@xB}@}Kg@oAhA_Hl@',
  'jlTgjNrFd@jI?A[mE{@oJp@',
  '|uQ{fNfHh@`Dm@tAkANqAwJRmFdAt@fA',
  'jpRohNmApAnSuA|LGaE{@pFo@LkAc\\bByC~A',
  'woSmhNfb@lAkJeGeDWoS~Bx@nA',
  'aqBcqNqSrCtNnAnBpCnDd@|AdDpFFlLyBuDgAjHw@dKiDzC{CaPgAmBdA{GAkAeAeHE{FdA',
  'a~CquNgKdAhHjBbQVjQa@b@u@~GCxE{AiRw@aHn@iE{@yNp@',
  's~HmvN`Mh@Z^fF`@xEo@qB}@zLEuTe@g@t@oHqAgHj@jA\\',
  'soR_lNrLVlPw@jImAvCmCpGg@gOgCoLm@cKbBmM`Ep@rD',
  'z~O{pNqF~@rGz@pJtC~IL~KWtEqAAgA}Cu@jJ@|EcA|ByAuGuCkEMvAm@qMI_GjBwSnA}CbC',
  'bkLmfOc]h@mJt@Ft@`c@jDsLA|WpDtIbDzK`@~Bf@|QTsGVhCb@eD`BrN|B|AlAvGz@[l@uIGCn@tOvBhOu@jQ\\bTa@X_BqJm@`BoCyBMuOtAnG_CbIe@aDmAaJo@y@eAzGmArAeB_U\\wHgA|b@K`JcAnKiCj@cA{[mAeHiAwFHwEv@wCkBmRu@mULaQa@aZV',
  'jhD_iOaf@|CnJlApx@ZcBb@cUU{QbAcK{@eDfAzErBgm@wCwQd@oBtAnXlCnBl@~R`@oMHhKrGE|EoF`CxHHfI|@qJhBm@hDtEPcGjDzLNgFnA`AfApP\\{FfCAxAjKsAdBt@mGp@eGxBkA`DdJd@nK_EcAfCfFfBaXRv`@jIdXdAlEjAtGrElLjCrTfBjDzB@jCdBbCdI~CoAzC~DfJxGJdHaDnKA`EmBdCaExIyFdBaCZsDrGwDgAsCdCeAeEiFkHiAoAsAi@{CdO`CrFaALgCmAiBqQp@hOcEfEZdDo@}E{DfOgL~FmAAsAvOsBdl@FbQ}D_\\iAvYs@bMoA[mAqm@_EmAiAzOgAmDoAsTiCcHUrAyA_a@sAgRAyE|@qOmBuc@zCzMkB[uA}SwB}TH_GiA_gAD',
];

/** Land borders between countries, as open lines. */
const BORDER_PATHS: readonly string[] = [
  'znXouIoBaBD}BrI}BhIsJfLsGhKnD|HyEfK}@Awy@',
  '`{UkjEaNc@Pd@uVnFkPA?qAyI?eH|EsBtEgBz@eDz@}B}CcDCkCnA_HnJcBhFwJbB',
  'l_Q{yA?mC_BcDaG?CcAhEgDyA??qBsJ@',
  'xjPibBz@?Q_K',
  'lmPcyAiDpB_CGMdB',
  'v`PcpAuBw@DaBcCy@{@f@oD}D}A`@cGkA',
  'peOmr@q@kCh@mBkAQ',
  'ziOkcAn@h@xCeAnEA',
  'lbNeu@UpCd@z@~@MX`B',
  'x|LshA~B`@zDfFlAbGeBJeAfC?dE_BtAuJDkCjDyK?~A~HgBjFdBbB}BpB{@fE',
  '`vM\\[vC|@`CzEpEnFlA~CtHpBpApAeBbDC[mE',
  'pqLlcAjEJMoHbDtBnDEjAiBdCKi@uA`EmHu@wBwBy@RkBaAcDcLkEsDH',
  'naLbvIlIE?}L',
  '|kLzeInSy@rAsBCuCdCJdAgAPsEyCwA_A_CVcBsDsLTuBwAe@TiAzAg@aAsAzAkAl@gFoAg@`@sFeB}JwBiA|@yJwCaCDgDqBcEAwDpC}J{BkEPaEeAuDoGwHx@mAa@mKyEaBk@aG',
  'dlJ|rE_DaV',
  'ltIz_D^nDtDxC|C^hLuAeEoH\\wAdR_GnJeI',
  'pjJb}B{@lBLnGsEd@qAe@eCt@oA~H}EJbAvI',
  'ntJis@|CtBPfAcAjAjDbAp@rCgCvC',
  'j`J{J~CInFfC|EgB~@aEuAoFpByBYwAtCe@',
  'vsImM`Hg@DhCjBO',
  'zaI_Y~FvKzHe@',
  'qpUaa@R`F~AEh@bAzAgB',
  've@uoIpGe@g@kBf@iB',
  'lgB}sAeIy@mAp@_C_@i@v@vQfA',
  'ctD~sDeAz@~A`DrC~AfARtCyCuEmE}Ag@wA|@',
  'du@{kDBbJnSIE~NxDPp@dBe@~GnW?h@`A',
  'fu@gjDoVdN',
  '`kAkzAcCrL',
  'rtAumAFzC|Dv@vA`B',
  '|fAwlAIfAsAYmDhAoE}AuCvDn@rBcABq@rB',
  'nfAmi@qFcI',
  'vs@ao@^rFmEvCZlG',
  'ss@}eFf@fB_@|Dn@bDzBnBQvCaHvFsAdJ',
  'yfAcnEJxCfHdECfD`Bl@',
  'g|CidEfA~A_@tAr@zB{@~C?fl@',
  'uYwvB?lMlBdCNxB`Mp@hAdA`CF',
  'iAi|AKzDoB`CE`BgFj@DhC',
  'zPe^jA{FgCiKt@{G',
  'sEad@`BcE[wGhC}O',
  'sDwcAXhBcC~Bm@jCFjMq@hC',
  'mLsiAkC{@wCrB',
  'qU{gAMqDiCoFuEWsGtCcEk@qFdBkKoBeGdAkEgB',
  'meFohCdiA?',
  'y{A{mCq@tH_DvD`CnV~F|DtAdGsAhA@`CaCBR|A',
  '_tCkyBIxWlDMnClGi@n@`Az@WrAfAzCeAKqBlH',
  'o~Akm@rClFJjHsGvI]rC',
  'oeAcMAnFfJH',
  'wpAeMg@~DgETvAfF_BtBB`H|@|AnDGhB_BNvAjEjAkAbCxClB',
  'acBeM_FcHgGl@',
  '{mCsdAiCpE^bDsAvB',
  'ubFcyAgFh@_AuCwBxAuBm@yDj@mDnAaHzH',
  'c}D`FoApBJtBx@V',
  'mtChcAUjK`LAFzRiG~G',
  'cpCnlBcHa@oAl@\\Z',
  'mgE`fDf@xAtBTtBmBeAiE_DT',
  '{|CzmBsDtHwHpF{@dEyGvB',
  'e|D|_BMhAeDCoIhDd@lUdHdK',
  'lw@wdGyCoAq@`BkGQw@bBzAt@j@vGtANoAvBt@bCcAx@dB`CQ`A',
  'uQmhGfFX`F{AfAj@nJyAnAmA',
  '_}@svItGB',
  'ue@ctH}JvA|BvG',
  'gwA_oIm@dBv@t@}DtJ',
  'g`AadHyBZ{EiAm@dA}Gr@',
  '{yBesIeRRuCrA_ArFvBf@eDbJlHtFs@xAhFwAbJp@dBeApAXfBmBrCKR}@fCU\\p@jBg@Kw@rFqA',
  '}vCehJiDc@cG`BeD@',
  '{mDwrJ]b@lCrB{@xDtA~@',
  'coDa~ImFbBkHVTrCaEjE_EvArGv@_B`E',
  'ej@gmIc@bAp@tDp@jAvB?a@pE',
  '}cC}wIiH`ADhB',
  'sbCe}IcF}@sOEeItC',
  'ytBktHxJrD',
  'aiCsmH{BjBxBh@vElG~NnBdDe@|GsD',
  'irBohGUa@pDkA~JeJi@qAgAl@gCm@qKhA',
  '_lCyqHhCxCtE{@jQjDnDgA',
  'ofBsaH|Cr@vA|C`II',
  'keDklHmHxGSfG',
  'oqDepGfG}AlI`BlOYv@qA',
  'slCmsGp@j@QhAaBtA|BpD',
  '}lCgjHuAk@yIfA}I_B',
  'ueEsdIgKo@_CpB`@dB_DHcA|B}FdAwC]{BzA{K~@nAbDm@lB^`A`ELdBv@FxA',
  '_nDqeGjDYjE|@@bBtDRlCeArHn@LcCbB_A',
  'mnCkaG`KbB',
  'gbDmdG_Bt@jBrC',
  'kbCg~FlDpF',
  'ubGsbGuEG_E`B',
  'wxFonGeNj@sHdCsHHyD~Bp@ZaBjBlIM',
  'uqDsnLZjCqHbCxDvCiF`FfCjDsDtCnA`CgHfCjAdBdRrJ',
  'g|EwcE~AjK',
  'mqFsoEqArF',
  'yjHkzDdCOpC~D',
  'qnHazDnBgB@kB|@@_@qCfBwCrFmBhC}Dm@{CcBcALuBbC{@`CmF',
  '_pIogFoDe@mCqBkJM{JzBeFnDsCFQfD',
  '}jIagB|EuM',
  'kjGeeBwA_A_@uDqAr@oQFq@`A}Aa@mCqE{DyA_QkA',
  'a`C}nLaQhFErHaAlA',
  'smHmqDlCBp@}ApDS',
  'o_JwzCdB?Q|CxAf@~@rF',
  '{qH_aHdB_@SgB|BcCrCBhDeCqBwCx@i@_DyEmErBWsC}KwEwHEeTzEsEsA{HC_GdBy@y@yGFq@}AbIiC_EaBd@u@_Es@nCiC{AcAkVcAiWoEgJj@}@nEoEq@aGbANlB}DKuN{DfA|@}FzC_MzNiBiBsGrB}Gs@oLrGaG[iBxB',
  'ozLegG{@RfD`CsCjAmCq@mFfB`GnChFMMsCjGl@|CnFfDIr@vAsCn@i@rCnBhE',
  'w~KohFxC{@^dAfDf@f@~CnGxAh@zAtCXjEkA',
  '}fLegFmEe@cAd@_A{AwBBiCsDkBl@SlFmA`A{GwCwIN',
  'stNugG|KfF`GVhA~B|IJ~D~A[l@v@l@',
  'okMmuFq@vDyDXW~D',
  'i_RsoDMjAdAb@OzBlCc@bGhCGpBpElLzCm@^fJbBn@',
  'wePgmDjM_A|H_C`A_BxH_D~C{@rAn@',
  'ajPsiDqFgEoIhB',
  'i`Qe`CLaDeA^CoC',
  'i_RsoDsBOyCdD@|H|DfDVjFsE_@o@vD}Bd@x@dDkFnBqCy@EpA',
  'wpRs~BuA|@KvBeCHj@dKqEwBqD\\g@eAwCLwC`DKdEaDlDHhD~@xA|LF~BfDm@nF',
  'kwR_eCQn@iBD\\eFgB[',
  'c~SwwAm@bCVnFnIxCwAxBpELlDnA',
  'q}RkkCmMgAiDiBwGnB^pB}ApAiEr@',
  'k}R{e@`ApAbCVLeBbDwA`@b@',
  'w_V{XpKa@xF~P`Dh@|Dw@rEvB`GXfCqB`@eC',
  'mcPcsH_[kH_K~@eC|AgNv@aEiCnAuBmEoEaS|Ce@tC{GrAyL_AgEZ}HdEsL\\_MqAcHmCaFvAmFO',
  'ugWqxFgOyJ}A~@mDD^gBuHuAmAqBaCtB',
  'eaXipFrLjD',
  'gpZfOEvg@',
  'miAn^mCwBkAbA',
  'yuBkwGgA?p@vA_BjAjAfB',
  'snHidGvCbCzGmC',
  'ugGugFrElDQpChApFzLnE',
  'qkEszEwFN',
  'cwB_oGoElC',
  'axGy`GwDlEv@~@mDvAEhC',
  'v~VgqH_lD??kAcAAaBnCyOhByMVqDw@{TvGw@zA{AMeCfBV`@oE|AqAbJbEhHuAnAmVkFl@yByA_@{J?eKqG_TAiDyAcCuFwCwCaHjA?pGaCnB',
  'aoFooBdBpBpE|ArAzN',
  'uiH_q@tPvQbGFfJnE',
  'sdGoWhC?nAcApFfD~Gc@jMkF',
  '_tFf\\|GgELsBvVmL',
  'du@{kDVjBfOn@|EdLtGvE`ArGhB`D`MN',
  '}cA{nJ}F{FaAiF~BeBJiGaC{DeEBeAoAfAcAaScS_E?s@oByJ^]cC{BG',
  '_{Fn_A~CrBxKdCdQI',
  'wkEtx@}AxAs@hDjAvEg@dDzB|FgBr@',
  '_wE~fAv@vCw@bGmC|@sAnCO`GtAh@|@hC`C{BOyHxF_C',
  'u_E}TJhFoAZ`G~Hz@bK',
  'm}D`Nw@|DfExEpAH',
  's}BqjGmB{AaEtBf@tA',
  'd_MyoBn@qBq@a@@wD',
  '}pHifA@fKdF`H',
  'gyEkwD`CwI',
  '{~E_oE}CwD^mAxAI',
  'e}EoiEhAYh@bCs@Vz@nA}AY',
  'gtD_{@gEiCgDrBeBSqE}F`AqDwBIMm@}AL?bHeBlAo@lD',
  'itC{t@aC{@iBmGoC[_EzDwEY',
  'qsEqYzBzAlHl@|Bk@rAt@',
  '}lD_{@[f@gE?Eg@',
  'k_Fy[hHCnAjA',
  'csEp{@f@u@bEe@',
  '_wE~fAzBmJ',
  'pLyzEqEvNd@lA',
  'dGshErMzBFrChFnAjAbBjJrA`IrC?jF',
  'oeNy|EuEhFR`D',
  'c|PqlD_DY}KsGeDp@oCsA}AzBbArAwE\\',
  'ddJid@^rDvBr@XtCwApC',
  'fpI_c@fBjD}A~F`@tA',
  '~fJyS_A?sC|G',
  'kjGicAj@fA_FtGmSjFgD?',
  'sdGoWnDbFAvUwBbD',
  '_pEi~Gs@q@eG~A',
  'kuMuhEhDrBAlCnOdRfFO|EpEcCxAUxCoBbBg@jDvL?bCdC',
  'pzJo_@Yv@hAjAfLxCxIy@yAr@SbGiDPIh@lCv@VtAdFlAf@|@zCLlBiB',
  '}vGewF}Dn@oApC',
  'axGy`GtG^',
  'koGy_GOfDaFjB',
  '}vGewFfCv@}@dFd@|@kB~C',
  'yvGigF~A`@dAs@|HD',
  'ugGugFtPdBlGc@zEv@`Ag@HnBjBvA',
  'mqFsoEfKtE`FqA',
  '_tF_hEvL`CgEfEbBdBvCXdCdC|E_@',
  'abH{tDrJOrPqKxOaE',
  '_dIwuBwQgEeCoKzAmC',
  'axI}lCf@h@xQcBrAyF',
  'q}Jy}EfChKuA\\rAlBoA|GwC`@O~BtDtD',
  'm{JmyDsD`F_EvAEnD}A^QzA`HfBhAfF',
  '}fLegFdGi@',
  'w~KohFEyBzMwDfJgF`BmExG[lAi@R}ClGiBrIvDa@dB`F@',
  'wtMagFtSzBtBvAeAvD`BrAn@rC|DEmAbC|Bp@tAxBKvBlAv@bFFTv@rC?nBnBDhDbGrArN\\nIeB',
  'okMmuFzJ\\tF_AxELSqByE^gA{@',
  '_aPsrHvCdCdDPHhEnBxAjKaAnCdJpNzBsDzIhCr@OpB',
  'stNugG~EeBzTC|GsAnBh@^tBhIeA`C\\l@tA',
  'ozLegGxJpDvAlChA@t@_B~FEf@cD`B?OiEnFqC`Ql@|DuD~NkF`OtBG`V',
  'y|IeaGdBHjC{CfCw@zHjB',
  'a~Mu~EmFz@',
  '}yNs{D|BxAlAzDaS|GsGXqBbBqP~@KeH',
  'ajPsiDyDrBiMWMyBnA_A',
  'ebQwhCfB}Hv@@^|BlBeB}@qByAK{AiDjNy@PkC|F_BdAfCoChBhDrC{Bt@`@vBcBxH',
  'kwR_eCrEjE',
  'wpRs~BfFdClCFxAvErAb@oHdMfAlDdAd@uD`GaBbKnEfK',
  'q}RkkCmEpIwF@kAlDvDzBmFvB{LfPq@lCb@fE',
  'c~SwwAnDiAzAhCbDmA',
  'qiDefJ_Bl@qAtE',
  'coDa~IpIlB',
  'ueEsdIjDJhAnCt_@uBfJ`A',
  'qdDszISxAbD~@l@pBzKhA',
  'a`C}nLuBs@_FhB{Md@}DwAaBsCuHaAaGlAtAlC',
  'uqDsnLuNcB',
  'keDklHsDq@eFdAwF`HUp@r@LrDQ|B|D',
  'moDi{GqGf@',
  'slCmsGd@c@o@a@nBRtBy@NqAzF}D',
  'kbCg~FpAq@ByC',
  'yuBkwGkAkAnBeC',
  '{|Am~HlCA|KhDw@nCwEdC',
  '_tAopHnCtBIbD|Cm@~HXZt@`Dm@',
  '}z@ahHtE{@pEh@',
  '_iBwnHtIwAtD~ArC_A',
  'ciBwkHNpAnB?e@h@`A`C',
  'gdBycHxHrAbDO',
  'g`AadHNpAjFFh@nA`CWpEjAtAi@',
  'um@shHpCNEp@pCnBBzA_B_@cAvA',
  'wi@m~Gs@bCdAz@s@zCkBVTvA',
  'mb@qtHlD{AdBNhFmDzAC\\eA',
  'oe@o|HlFgCjIX',
  'v]a{CpH@aFvu@j@jC`X@zEfAjEs@^tBbAb@',
  '`kAkzA|F{GbFoBrHZbA~@',
  'gz@m|DkAlGZhNnArAcEtI}Ac@uFxE',
  '_jAuqCnf@dWxGvA',
  'uYwvB|ER@}BxEyAn@}Abi@gZ',
  'y{A{mClChAnBmBzHuA',
  'g{CohC?nKdF?@rA',
  '_tCkyBzp@}VhElB',
  '{mCsdAbFpBnCxEzD|AxFDSdA|DrCvO|A',
  'o~Akm@_@u@zA}ElEuCk@}AcGFlBuDDiGlA_C',
  'swA_mAoAlA^fBhDxCjJzVhCbAzDoApDvBpClI',
  '|fAwlAtL]',
  'dq@y~@v@rA_BpF|Ar@Z|B',
  'vs@ao@xCjAlBuF|AX',
  '|~@qs@v@JTwDbB{CdGh@bDzD',
  'iAi|A~GGxDpAzEjEtDLrAxD|CdDb@jG',
  'v`@y_A`Ct@^sA~BjAjFM',
  'mLsiAxFzD',
  'tPg{@fCs@bDx@tEwC',
  'C{cAnQJUfG',
  'qU{gAS~HdEtHD`M',
  'acBeMLjB~HcBzFG',
  'wpAeMfJ@',
  'oeAcMdIC',
  'ysCeu@cGfDA`AyE|Ds@vBsDnC',
  'ajDu_@vIEfDfAnAi@|EbBzAStAfCfHy@bHmCxDdDPjC',
  'ubFcyApBnJvBbBhBhF|Av@z@pE',
  'gsE{z@XnFjBDbApB{BLeB~AsFvI',
  'kjGicAjEWRsBiCuD',
  '{rE|D@sEeFgJlEsM',
  'u_E}T|EyEzId@xBcD',
  'irB{TlB~Ir@nLtFfGvA`EGdD|G|GvA{AbFt@',
  'gpAz\\bDhE',
  '{wDjGnBjH',
  'ktDvP_AjI',
  'kvDb[w@rKsBnBkBzF',
  'c_Ebs@zILlBtCk@xAz@rLaEpBw@c@OvExCAxCcExC[l@gBxB|@~C[`AyA|EMH}@dAC',
  'mtChcA|I\\ImF`AiA\\}LrF@QgAdB?dCj@nAdDtHNbFuL`Xj@',
  'm}D`NhBK|@pBxBO',
  'c}D`FwTc@',
  'wkEtx@rKqD',
  'qnEhvA|QdDQlC',
  'e|D|_BfGhB|JzJfKw@',
  'cpCnlBnJpAbN[jC_BfYTvByAxI`A',
  'yzCvmBlGnBjAqAhMjADfUbEF?fQ',
  '}vD`iClMfH|BpElBNv@|C`Hb@rDoArIbHnCRX_EjD{E',
  '}aE`jC~I_@',
  '_fEn`DQeHrCgL',
  'lmPcyAg@aCwDcC',
  '~`LyFd@V|AuD`AdAdKCCzBsBRDlAxCJ?pCwBxD|AzR',
  'xsLzY~CoB_CiEvC}AbMHtBqE`HoFr@P',
  '`vM\\vDqB`FBp@uAlFmB',
  'lbLbmCnCXxDsN_A_EhBuAzBwG',
  'pjJb}B@}@zDeBtOt@rDjO',
  'ltIz_DcBe@cBpBB~ClH~DlNrM',
  'dgJz{DaCU}RbKsBfCvA|Aw@pB',
  '|qLzlB}BwEtAgDm@cAb@iAmAcBw@yJjDaI',
  'grAwsAkDvE',
  'k_HcqFfCYdCgD',
  'uaHiqFuHaD{@x@dAbBmD|A',
  'rtAumArQh@',
  'k{BxyC@`V|GtBtEu@pBkC~AbB',
  'xfK`jCbGs@lA`DrBoCdGq@fDtD',
  'pqLlcA{FJcIwEeGa@JhJwEpD_F`@iHjDqFx@q@bGx@@kAhF_KFF`EmBv@m@zBxAtFSpB~@h@',
  '_aPsrHmAOs@jCgDhB}GjAiC~CjAhFgAtAyN|@mJrCoElHc[LkNtCqF?yA|@gFiBwYsC{GmD~AoCgB_C}Hx@yNwD}G{D_MCUgAtIkEvChAvHEp@qAmF}I',
  'gxUyvHoFjAyG}B@wAcHsG@oBlBm@cDcBaOi@{MdCuI|Q{I~@kFlCqAzDoH?wNiC`KzSrFc@hDdAs@jD\\jFdBDAbB',
  'stMgwErD]`BtAkCvH',
  'abNazErAnAxIH',
];

let decoded: { land: Point[][]; borders: Point[][] } | null = null;

/** The outline, decoded once and kept. */
export function worldOutline() {
  decoded ??= { land: LAND_PATHS.map(decode), borders: BORDER_PATHS.map(decode) };
  return decoded;
}
